version: "3"
services:
  db:
    image: mysql:8.0
    container_name: ticket-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app

  admin:
    build: ./admin
    command: npm start -- --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - ./admin:/app

  client:
    build: ./client
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app

volumes:
  db_data:
